

# The namespace to deploy the Schema Registry into.
namespace: dataphos

# Images to use.
images:
  initdb: syntioinc/dataphos-schema-registry-initdb:1.0.0
  registry: syntioinc/dataphos-schema-registry-api:1.0.0
  compatibilityChecker: syntioinc/dataphos-schema-registry-compatibility:1.0.0
  validityChecker: syntioinc/dataphos-schema-registry-validity:1.0.0

# Number of replicas of the Schema Registry API.
registryReplicas: 1

# History database.
database:
  name: postgres
  username: postgres
  password: POSTGRES_PASSWORD
