
# CSV Validator
{{- if .Values.csvValidator.enable }}
apiVersion: v1
kind: Service
metadata:
  name: validator-csv-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: validator-csv
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: validator-csv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-csv
  namespace: {{ .Values.namespace }}
  annotations:
    "syntio.net/logme": "true"
spec:
  replicas: {{ .Values.csvValidator.replicas }}
  selector:
    matchLabels:
      app: validator-csv
  template:
    metadata:
      labels:
        app: validator-csv
    spec:
      containers:
        - name: validator-csv
          image: {{ .Values.images.csvValidator }}
---
{{- end}}

# XML Validator
{{- if .Values.xmlValidator.enable }}
apiVersion: v1
kind: Service
metadata:
  name: validator-xml-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: validator-xml
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8081
  selector:
    app: validator-xml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-xml
  namespace: {{ .Values.namespace }}
  annotations:
    "syntio.net/logme": "true"
spec:
  replicas: {{ .Values.xmlValidator.replicas }}
  selector:
    matchLabels:
      app: validator-xml
  template:
    metadata:
      labels:
        app: validator-xml
    spec:
      containers:
        - name: validator-xml
          image: {{ .Values.images.xmlValidator }}
{{- end}}
