# Default values for dataphos-schema-registry-validator.

namespace: dataphos

images:
  validator: syntioinc/dataphos-schema-registry-validator:1.0.0
  xmlValidator: syntioinc/dataphos-schema-registry-xml-val:1.0.0
  csvValidator: syntioinc/dataphos-schema-registry-csv-val:1.0.0
